export const IconTags = [
  "arrow",
  "navigation",
  "direction",
  "movement",
  "pointer",
  "24x24",
  "icon",
  "symbol",
  "interface",
  "graphic",
  "down",
  "corner",
  "turn",
  "angular",
  "shape",
  "left",
  "navigate",
  "back",
  "previous",
  "right",
  "up",
  "scroll",
  "point",
  "indicator",
  "web",
  "button",
  "pause",
  "stop",
  "diagonal",
  "pointing",
  "interruption",
  "termination",
  "diagonal arrow",
  "end",
  "terminating arrow",
  "arrow icon",
  "bottom-left",
  "top right",
  "bottom left",
  "split arrow",
  "top-left",
  "bottom-right",
  "tl",
  "br",
  "halt",
  "top left",
  "bottom right",
  "split",
  "user interface",
  "interaction",
  "directional",
  "transition",
  "arrow down",
  "copy",
  "duplicate",
  "downward",
  "action",
  "content",
  "move",
  "item",
  "UI",
  "scrolling",
  "download",
  "downwards",
  "file transfer",
  "data transfer",
  "corner arrow",
  "arrow head",
  "pointing down",
  "angle",
  "upward",
  "rightward",
  "arrow-headed",
  "upwards",
  "UI design",
  "graphic design",
  "moving upwards",
  "higher level",
  "progression",
  "design",
  "top-right",
  "dynamic",
  "separation",
  "division",
  "bottom",
  "top",
  "triangle",
  "arrowhead",
  "down arrow",
  "instruction",
  "decrease",
  "triangular",
  "arrow-headed-download",
  "technology",
  "internet",
  "centered",
  "focus",
  "central",
  "location",
  "guidance",
  "pointy",
  "vector",
  "inward",
  "options",
  "choice",
  "switch",
  "interface design",
  "app",
  "traffic",
  "warning",
  "sign",
  "safety",
  "Left arrow",
  "Pointing",
  "Direction",
  "Navigation",
  "Back",
  "Symbol",
  "Arrowhead",
  "Simple",
  "Minimalistic",
  "expansion",
  "zoom out",
  "external",
  "refresh",
  "reload",
  "circular motion",
  "digital design",
  "circular arrow",
  "update",
  "opposite direction",
  "loop",
  "restart",
  "circular",
  "symmetric",
  "opposite",
  "sync",
  "return",
  "motion",
  "revert",
  "undo",
  "website",
  "reverse",
  "forward",
  "next",
  "progress",
  "simple",
  "minimalist",
  "basic",
  "rotate",
  "counter-clockwise",
  "rotate icon",
  "rotation",
  "angled",
  "change",
  "previous state",
  "rotate object",
  "rotate element",
  "rounded",
  "share",
  "transfer",
  "spread",
  "communication",
  "social media",
  "networking",
  "information",
  "flowchart",
  "divergence",
  "paths",
  "splitting",
  "branching",
  "diagrams",
  "expand",
  "growth",
  "distribution",
  "two-way",
  "lr",
  "bidirectional",
  "exchange",
  "twoway",
  "Horizontal",
  "Two-way",
  "Arrowheads",
  "Movement",
  "Interaction",
  "Opposite directions",
  "Directional",
  "Communication",
  "vertical",
  "toggle",
  "sorting",
  "dual",
  "transport",
  "control",
  "alert",
  "upload",
  "send",
  "uploading icon",
  "center",
  "arrows",
  "inwards",
  "invert",
  "arrow left",
  "arrow right",
  "left arrow",
  "stop sign",
  "Left",
  "Previous",
  "Move",
  "Navigate",
  "Button",
  "outward",
  "renew",
  "renewal",
  "up arrow",
  "bi-directional",
  "curve",
  "back to top",
  "go to top",
  "cancel",
  "horizontal",
  "proceed",
  "clockwise",
  "spin",
  "turning",
  "reposition",
  "leftwards",
  "connection",
  "collaboration",
  "branching out",
  "directions",
  "decision",
  "separate",
  "diverge",
  "shift",
  "flow",
  "swap",
  "mirror",
  "relocation",
  "position",
  "leftright",
  "right to left",
  "horizontal arrow",
  "reversible",
  "cycle",
  "collapse",
  "selection",
  "Sort",
  "Scroll",
  "UpDown",
  "Vertical",
  "Arrow",
  "User Interface",
  "increase",
  "elevate",
  "ascend",
  "data",
  "file",
  "chevron",
  "connect",
  "link",
  "arrowheads",
  "interactive",
  "network",
  "disconnect",
  "remove",
  "modern",
  "sleek",
  "chevron double down",
  "reveal",
  "web design",
  "double arrow",
  "arrow symbol",
  "double",
  "process",
  "stacked",
  "page",
  "show more",
  "dropdown",
  "menu",
  "select",
  "restaurant",
  "beverage",
  "culinary",
  "refreshment",
  "eatery",
  "bar",
  "cooking",
  "dining",
  "snack",
  "drink container",
  "liquids",
  "container",
  "hydration",
  "glassware",
  "liquid storage",
  "drinking",
  "water bottle",
  "drink containers",
  "beverages",
  "plastic bottles",
  "storage",
  "refreshments",
  "containers",
  "drinks",
  "bread slice",
  "bread",
  "slice",
  "food",
  "bakery",
  "sandwich",
  "breakfast",
  "carbohydrate",
  "toast",
  "coffee",
  "cafe",
  "morning",
  "drink",
  "hot",
  "relaxation",
  "mug",
  "brew",
  "machine",
  "brewing",
  "dispensing",
  "hot drinks",
  "home appliance",
  "office equipment",
  "coffee shop",
  "alcohol",
  "drinkware",
  "liquor",
  "celebrate",
  "party",
  "luxury",
  "cocktail",
  "espresso",
  "coffee culture",
  "morning routines",
  "caffeine",
  "espresso maker",
  "Espresso",
  "Machine",
  "E61",
  "Coffee",
  "Barista",
  "Brewing",
  "Cafe",
  "Hot Beverage",
  "Bar",
  "barista",
  "hot drink",
  "kitchen appliance",
  "pistol",
  "burger",
  "fast food",
  "digital",
  "popular",
  "device",
  "hot beverage",
  "coffee maker",
  "celebration",
  "nightlife",
  "winery",
  "alarm",
  "bell",
  "notification",
  "reminder",
  "sound",
  "ringing",
  "emergency",
  "clock",
  "loud",
  "urgent",
  "attention",
  "media",
  "art supplies",
  "painting",
  "drawing",
  "creative",
  "artists",
  "crafting",
  "materials",
  "tools",
  "inspiration",
  "hobby",
  "audio waves",
  "sound waves",
  "music",
  "audio visualizer",
  "waveform",
  "song",
  "audio",
  "music player",
  "acoustic",
  "photography",
  "video recording",
  "multimedia",
  "picture",
  "film",
  "capture",
  "snapshot",
  "paste",
  "notes",
  "document",
  "record",
  "save",
  "text",
  "art",
  "color selection",
  "creativity",
  "digital art",
  "palette",
  "color picker",
  "RGB",
  "color channels",
  "spectrum",
  "editing",
  "graphics",
  "visual",
  "color",
  "swatches",
  "tool",
  "artist",
  "computer",
  "desktop",
  "icons",
  "shortcuts",
  "files",
  "organization",
  "screen",
  "computing",
  "camera",
  "analog",
  "vintage",
  "photo",
  "photograph",
  "retro",
  "cinema",
  "roll",
  "video games",
  "gaming",
  "console",
  "controller",
  "joystick",
  "entertainment",
  "classic",
  "arcade",
  "leisure",
  "electronics",
  "fun",
  "highlight",
  "mark",
  "emphasis",
  "important",
  "images",
  "artwork",
  "portable",
  "work",
  "laptop",
  "keyboard",
  "email",
  "envelope",
  "message",
  "inbox",
  "correspondence",
  "open",
  "letter",
  "outbox",
  "contact",
  "video",
  "player",
  "microphone",
  "voice command",
  "sound input",
  "messaging",
  "recording device",
  "note",
  "single",
  "melody",
  "musical",
  "tune",
  "listen",
  "video game",
  "character",
  "yellow",
  "eating",
  "maze",
  "ghosts",
  "flight",
  "backward",
  "skip",
  "media player",
  "rewind",
  "play",
  "skip forward",
  "fast forward",
  "advance",
  "track",
  "playlist",
  "playback",
  "pause button",
  "start",
  "media control",
  "beginning",
  "office",
  "equipment",
  "printing",
  "paper",
  "paperwork",
  "output",
  "print job",
  "record button",
  "streaming",
  "movies",
  "videos",
  "film reel",
  "old-fashioned",
  "nostalgia",
  "projection",
  "traditional",
  "tablet",
  "landscape",
  "display",
  "touchscreen",
  "gadget",
  "television",
  "broadcast",
  "watching",
  "shows",
  "channel",
  "program",
  "code",
  "programming",
  "command",
  "shell",
  "developer",
  "system",
  "administrator",
  "IT",
  "recording",
  "recordings",
  "clips",
  "footage",
  "mute",
  "speaker",
  "volume",
  "adjust",
  "level",
  "sound control",
  "volume up",
  "volume down",
  "audible",
  "third level",
  "silence",
  "no sound",
  "quiet",
  "no volume",
  "volume control",
  "mute icon",
  "Internet",
  "Online",
  "Web design",
  "Digital",
  "Technology",
  "Browser",
  "Homepage",
  "URL",
  "Hyperlink",
  "Search",
  "unique",
  "special",
  "decorative",
  "artistic",
  "distinctive",
  "baht",
  "currency",
  "Thai",
  "money",
  "finance",
  "economy",
  "foreign exchange",
  "currency symbol",
  "Thailand",
  "dice",
  "game",
  "random",
  "number",
  "one",
  "luck",
  "casino",
  "probability",
  "chance",
  "two",
  "gambling",
  "dice roll",
  "three",
  "randomness",
  "games",
  "dice game",
  "board game",
  "cube",
  "rolling",
  "numeric",
  "numbers",
  "board games",
  "activity",
  "seven",
  "random number",
  "game interface",
  "nine",
  "digit",
  "2",
  "numeral",
  "tech",
  "stylish",
  "Three",
  "Number",
  "Counting",
  "Digit",
  "Modern",
  "Sleek",
  "Typography",
  "Numeric",
  "four",
  "quantity",
  "value",
  "counter",
  "digital style",
  "textbox",
  "five",
  "counting",
  "six",
  "futuristic",
  "special character",
  "calculator",
  "electronic",
  "eight",
  "score",
  "typography",
  "zero",
  "financial",
  "dollar sign",
  "business",
  "wealth",
  "payment",
  "cost",
  "cash",
  "eurozone",
  "Europe",
  "banking",
  "math",
  "statistics",
  "percentage",
  "ratio",
  "proportion",
  "pound",
  "hash",
  "number sign",
  "coding",
  "tag",
  "punctuation",
  "permillage",
  "concentration",
  "blood alcohol content",
  "mathematics",
  "unit",
  "measurement",
  "label",
  "fraction",
  "Russia",
  "ruble",
  "Russian rubles",
  "Indian rupee",
  "INR",
  "monetary unit",
  "India",
  "monetary",
  "female",
  "gender",
  "woman",
  "restroom",
  "feminine",
  "ladies",
  "feminist",
  "equality",
  "women's rights",
  "Male",
  "Gender",
  "Masculinity",
  "Men",
  "Man",
  "Icon",
  "Characteristic",
  "Information",
  "Identity",
  "gender-neutral",
  "male",
  "inclusive",
  "signage",
  "bathroom",
  "unisex",
  "healthcare",
  "dots",
  "more",
  "settings",
  "actions",
  "ellipsis",
  "three dots",
  "list",
  "context menu",
  "option",
  "kebab",
  "major",
  "points",
  "special characters",
  "minor",
  "intersection",
  "elements",
  "break",
  "spacing",
  "divider",
  "lines",
  "design element",
  "eye-catching",
  "Japan",
  "currency-symbol",
  "yen",
  "Japanese",
  "Asian",
  "AI",
  "artificial intelligence",
  "robot",
  "smart",
  "innovation",
  "mind",
  "blocked",
  "letters",
  "obstacles",
  "limitations",
  "access",
  "difficulty",
  "restrictions",
  "challenges",
  "Letters",
  "Circles",
  "Artificial intelligence",
  "Alphabet",
  "Symbolic",
  "Science",
  "merge",
  "logo",
  "typing",
  "wildlife",
  "nature",
  "step",
  "walking",
  "hiking",
  "conservation",
  "Artwork",
  "Frame",
  "Decoration",
  "Picture",
  "Gallery",
  "Display",
  "Interior design",
  "Home decor",
  "Wall art",
  "Design element",
  "cookout",
  "grill",
  "outdoor cooking",
  "picnic",
  "barbecue tools",
  "summer",
  "searing",
  "flame",
  "bathroom essentials",
  "toiletries",
  "personal care",
  "hygiene",
  "products",
  "shower",
  "bath",
  "cleanliness",
  "amenities",
  "exploration",
  "adventure",
  "observation",
  "view",
  "search",
  "find",
  "zoom",
  "distance",
  "magnify",
  "optics",
  "appliance",
  "kitchen",
  "mixing",
  "blending",
  "food preparation",
  "electric",
  "motor",
  "kitchenware",
  "books",
  "shelves",
  "library",
  "home",
  "decor",
  "literature",
  "reading",
  "light bulb",
  "ideas",
  "electricity",
  "illumination",
  "energy",
  "solution",
  "science",
  "invention",
  "semiconductor",
  "microchip",
  "silicon chip",
  "processor",
  "component",
  "circuit",
  "cleaning",
  "household",
  "chores",
  "bucket",
  "soap",
  "water",
  "cleanup",
  "sanitation",
  "maintenance",
  "spray",
  "cleaning product",
  "sanitize",
  "disinfect",
  "Storage",
  "Wardrobe",
  "Home",
  "Organization",
  "Room",
  "Household",
  "Clothes",
  "Shoes",
  "Personal items",
  "Beverage",
  "Caffeine",
  "Drink",
  "Ingredient",
  "Roasted",
  "Aroma",
  "Morning",
  "Bean",
  "savings",
  "earnings",
  "transactions",
  "orientation",
  "travel",
  "mapping",
  "geography",
  "north",
  "south",
  "east",
  "west",
  "geometry",
  "dimensional",
  "volumetric",
  "space",
  "perspective",
  "solid",
  "structure",
  "education",
  "learning",
  "school",
  "knowledge",
  "graduation",
  "pencils",
  "study",
  "teaching",
  "lesson",
  "Factory",
  "Arm",
  "Manufacturing",
  "Production",
  "Industries",
  "Automation",
  "Machinery",
  "Assembly lines",
  "Industrial revolution",
  "factory",
  "industrial",
  "manufacturing",
  "machinery",
  "automation",
  "production",
  "assembly line",
  "conveyor belt",
  "mechanical",
  "building",
  "facility",
  "plant",
  "workplace",
  "biometric",
  "security",
  "authentication",
  "identification",
  "privacy",
  "scan",
  "cooling",
  "food storage",
  "domestic",
  "chill",
  "refrigeration",
  "fridge",
  "Bed",
  "Sleep",
  "Rest",
  "Comfort",
  "Furniture",
  "Interior",
  "Decor",
  "Relaxation",
  "furniture",
  "bedside",
  "table",
  "nightstand",
  "room",
  "interior",
  "bedroom",
  "Chair",
  "Seat",
  "Sitting",
  "Living room",
  "couch",
  "sofa",
  "living room",
  "comfort",
  "seat",
  "lounge",
  "Desk",
  "Table",
  "Wooden",
  "Office",
  "Workspace",
  "Workstation",
  "Home office",
  "Furniture ",
  "cabinet",
  "drawers",
  "wood",
  "furnishings",
  "organize",
  "analysis",
  "chart",
  "round",
  "graph",
  "upward trend",
  "data analysis",
  "presentation",
  "report",
  "hairdryer",
  "hair styling",
  "beauty",
  "hair care",
  "blow dryer",
  "grooming",
  "salon",
  "hair tools",
  "hair accessories",
  "brainstorming",
  "creative thinking",
  "imagination",
  "strategy",
  "concept",
  "chimney",
  "smoke",
  "industrialization",
  "industry",
  "engineering",
  "metal",
  "material",
  "heavy",
  "silver",
  "construction",
  "iron",
  "workmanship",
  "strong",
  "cutlery",
  "utensils",
  "meal",
  "preparation",
  "silverware",
  "kitchen tools",
  "leaf",
  "green",
  "environment",
  "ecology",
  "foliage",
  "botany",
  "flora",
  "organic",
  "botanical",
  "fresh",
  "leaves",
  "plants",
  "natural",
  "soap dispenser",
  "liquid soap",
  "bathroom accessory",
  "household item",
  "body wash",
  "hand sanitizer",
  "disinfectant",
  "handwashing",
  "heating",
  "electromagnetic radiation",
  "meal prep",
  "quick",
  "convenient",
  "leftovers",
  "prosperity",
  "Wealth",
  "Finance",
  "Prosperity",
  "Savings",
  "Investments",
  "Business",
  "Riches",
  "Currency",
  "Earnings",
  "Cash",
  "Kitchen",
  "Appliance",
  "Cooking",
  "Baking",
  "Food",
  "Heat",
  "Temperature",
  "eco-friendly",
  "floral",
  "freshness",
  "sustainability",
  "politician",
  "government",
  "leadership",
  "elections",
  "public speaking",
  "speech",
  "public appearance",
  "politics",
  "politician icon",
  "political event",
  "authority",
  "election",
  "official",
  "candidate",
  "decision-making",
  "window covering",
  "shades",
  "protection",
  "interior design",
  "architecture",
  "light filtering",
  "room decor",
  "sunlight control",
  "Oven",
  "Burner",
  "Cuisine",
  "Chef",
  "religion",
  "worship",
  "faith",
  "culture",
  "historical",
  "ancient",
  "sacred",
  "spirituality",
  "Religious",
  "Spiritual",
  "Building",
  "Worship",
  "Faith",
  "Culture",
  "Tradition",
  "Sacred",
  "Architecture",
  "tree",
  "forest",
  "branches",
  "park",
  "outdoor",
  "trees",
  "greenery",
  "outdoors",
  "scenery",
  "woodland",
  "reptile",
  "slow",
  "patience",
  "wisdom",
  "longevity",
  "animal",
  "ballot",
  "survey",
  "voting",
  "choose",
  "poll",
  "shopping",
  "pocket",
  "credit card",
  "personal belongings",
  "wallet",
  "laundry",
  "clothing",
  "fabric",
  "detergent",
  "washing",
  "electric kettle",
  "boiling water",
  "hot beverages",
  "tea",
  "instant noodles",
  "person",
  "accessibility",
  "circle",
  "user-friendly",
  "disabled",
  "special needs",
  "easy access",
  "universal design",
  "Person",
  "Inclusivity",
  "Disability",
  "Diversity",
  "Assistance",
  "Support",
  "User-friendly",
  "Equality",
  "Inclusive design",
  "Adaptive",
  "plus",
  "join",
  "insert",
  "create",
  "fat",
  "thick",
  "add",
  "append",
  "new",
  "plus sign",
  "square",
  "address",
  "username",
  "handle",
  "email address",
  "block",
  "partials",
  "sections",
  "group",
  "arrange",
  "grouping",
  "board",
  "section",
  "multi-column",
  "layout",
  "dashboard",
  "boards",
  "vertical layout",
  "application",
  "multiple",
  "analytics",
  "expandable",
  "multi-directional",
  "multi",
  "columns",
  "grid",
  "panels",
  "tiles",
  "ui",
  "tabs",
  "multi-tab",
  "arrangement",
  "workspace",
  "multiply",
  "operation",
  "calculation",
  "calculators",
  "mathematical",
  "divided",
  "three columns",
  "divide",
  "partition",
  "interface element",
  "components",
  "segmented",
  "template",
  "effect",
  "element",
  "split view",
  "split screen",
  "segments",
  "subtraction",
  "delete",
  "minus",
  "deduct",
  "physical",
  "box",
  "enclosed",
  "packing",
  "inside",
  "packaging",
  "restricted",
  "context",
  "package",
  "placeholder",
  "rectangle",
  "containment",
  "child",
  "youth",
  "avatar",
  "kid",
  "profile",
  "human",
  "heartbreak",
  "sadness",
  "emotions",
  "love",
  "relationship",
  "romantic",
  "disappointment",
  "broken heart",
  "heart",
  "broken",
  "romance",
  "feelings",
  "place of worship",
  "holy",
  "Christianity",
  "religious symbol",
  "House",
  "Residential",
  "Real Estate",
  "Housing",
  "Property",
  "Construction",
  "Roof",
  "house",
  "real estate",
  "property",
  "residence",
  "dwelling",
  "shelter",
  "shop",
  "store",
  "commercial",
  "retail",
  "marketplace",
  "clickable",
  "task",
  "relationships",
  "check mark",
  "confirmation",
  "completion",
  "approval",
  "form",
  "check",
  "confirm",
  "submit",
  "approve",
  "validate",
  "edit",
  "pencil",
  "modify",
  "UX",
  "edit button",
  "editable",
  "exclamation mark",
  "like",
  "favorite",
  "emotion",
  "info",
  "details",
  "help",
  "tooltip",
  "informational",
  "click",
  "hidden",
  "inactive",
  "unclickable",
  "ui element",
  "web development",
  "invisible",
  "interact",
  "unseen",
  "concealed",
  "arithmetic",
  "question mark",
  "support",
  "faq",
  "query",
  "FAQ",
  "assistance",
  "search engine",
  "magnifying glass",
  "search button",
  "search function",
  "input field",
  "search bar",
  "UI icon",
  "lookup",
  "star",
  "rating",
  "outline",
  "rate",
  "subtract",
  "calculate",
  "visible element",
  "visible",
  "graphical user interface",
  "UI element",
  "calendar",
  "date",
  "schedule",
  "appointment",
  "event",
  "planner",
  "time management",
  "deadline",
  "time",
  "tracking",
  "bars",
  "visualization",
  "bubbles",
  "data visualization",
  "infographic",
  "stock market",
  "investment",
  "candlestick chart",
  "charting",
  "Graph",
  "Data visualization",
  "Analytics",
  "Statistics",
  "Report",
  "Presentation",
  "Dashboard",
  "Diagram",
  "line",
  "trends",
  "metrics",
  "reporting",
  "line chart",
  "plot",
  "pie",
  "tick",
  "complete",
  "confirmed",
  "success",
  "verification",
  "checkbox",
  "verified",
  "validated",
  "acceptance",
  "tasks",
  "items",
  "planning",
  "progress tracking",
  "to-do list",
  "management",
  "productivity",
  "validation",
  "approved",
  "correct",
  "unknown",
  "secret",
  "mask",
  "eliminate",
  "function",
  "addition",
  "include",
  "feature",
  "emoticon",
  "illustration",
  "ui design",
  "circled",
  "completed",
  "acknowledgment",
  "pen",
  "write",
  "hazard",
  "caution",
  "error",
  "exclamation",
  "affection",
  "like button",
  "favorite button",
  "valentine",
  "heart shape",
  "question",
  "multiplication",
  "FAQs",
  "discover",
  "importance",
  "eye",
  "visibility",
  "Enclosed",
  "Round",
  "Highlight",
  "Emphasis",
  "Attention-grabbing",
  "Circular",
  "Outline",
  "Graphic design",
  "plan",
  "hour",
  "minute",
  "second",
  "timing",
  "cloud",
  "lightning",
  "storm",
  "thunderstorm",
  "weather",
  "forecast",
  "climate",
  "meteorology",
  "rain",
  "precipitation",
  "sky",
  "weather forecast",
  "season",
  "sun",
  "partly cloudy",
  "sunshine",
  "thermometer",
  "temperature",
  "Code",
  "Coding",
  "Programming",
  "Development",
  "Brackets",
  "Circle",
  "Syntax",
  "Snippet",
  "Syntax Highlighting",
  "development",
  "syntax",
  "brackets",
  "code editor",
  "software",
  "coding standards",
  "chevrons",
  "nested",
  "open chevrons",
  "Commands",
  "Instructions",
  "Code Blocks",
  "Software",
  "Sequence",
  "Arrows",
  "corporate",
  "enterprise",
  "company logo",
  "branding",
  "dislike",
  "thumb down",
  "unlike",
  "reject",
  "thumbs",
  "negative",
  "feedback",
  "expression",
  "edit content",
  "document editing",
  "customize",
  "edit tool",
  "editor",
  "swirl",
  "writing",
  "edit icon",
  "simplified",
  "user",
  "minimalistic",
  "file system",
  "data management",
  "folder",
  "zip",
  "compress",
  "format",
  "archive",
  "compressed",
  "zipped",
  "binary",
  "corrupted",
  "inaccessible",
  "data loss",
  "problem",
  "depression",
  "status",
  "cloud computing",
  "backup",
  "script",
  "programming language",
  "spreadsheet",
  "revision",
  "modification",
  "notify",
  "graphs",
  "charts",
  "attachment",
  "file-heart",
  "inspection",
  "file info",
  "metadata",
  "file type",
  "information icon",
  "confidential",
  "discreet",
  "encrypted",
  "secure",
  "private",
  "replicate",
  "uncertainty",
  "unsuppored",
  "browse",
  "explore",
  "search tool",
  "searching",
  "favorite file",
  "starred",
  "marker",
  "file management",
  "File",
  "Text",
  "Document",
  "Content",
  "Page",
  "Edit",
  "Write",
  "Read",
  "documents",
  "stack",
  "tray",
  "collection",
  "records",
  "accessible",
  "visible file",
  "show",
  "directory",
  "folders",
  "Folder",
  "Broken heart",
  "Emotion",
  "Sadness",
  "Loss",
  "Sentimental",
  "User interface",
  "Folder icon",
  "Heart icon",
  "Symbol icon",
  "emotional",
  "distress",
  "loss",
  "symbolic",
  "checkmark",
  "folder icon",
  "document icon",
  "file verification",
  "folder check",
  "folder validation",
  "bulk",
  "file manager",
  "bulk delete",
  "multiple items",
  "clean up",
  "enquiry",
  "unclear",
  "confusion",
  "magnifier",
  "explorer",
  "Subtract",
  "Delete",
  "Directory",
  "Management",
  "flap",
  "contents",
  "expanded",
  "hierarchy",
  "organized",
  "digital organization",
  "people",
  "representation",
  "version control",
  "repository",
  "git",
  "workflow",
  "commit",
  "branch",
  "comparison",
  "difference",
  "changes",
  "queue",
  "versioning",
  "VCS",
  "merge process",
  "code changes",
  "pull request",
  "closed",
  "source code",
  "draft",
  "work in progress",
  "code review",
  "GitLab",
  "Bitbucket",
  "GitHub",
  "review",
  "source control",
  "fork",
  "small",
  "Valentine's Day",
  "dating",
  "health",
  "medical",
  "instructions",
  "notice",
  "guide",
  "advice",
  "tips",
  "explanation",
  "Hidden",
  "Inactive",
  "Concealed",
  "Invisible element",
  "Transparent",
  "Unseen",
  "Concealed feature",
  "Concealed content",
  "minimal",
  "hide",
  "eyes",
  "conceal",
  "stealth",
  "camouflage",
  "cloaked",
  "backspace",
  "shortcut",
  "input",
  "text editing",
  "key",
  "lock",
  "press",
  "eject",
  "safely remove",
  "log out",
  "enter key",
  "setting",
  "mac",
  "preferences",
  "entry",
  "page down",
  "pagination",
  "webpage",
  "modifier",
  "tab key",
  "arrow key",
  "flash",
  "power",
  "speed",
  "fast",
  "thumb",
  "react",
  "positive",
  "appreciation",
  "hyperlink",
  "redirect",
  "online",
  "loading animation",
  "loading process",
  "loader",
  "wait",
  "loading screen",
  "loading",
  "animation",
  "waiting",
  "sequence",
  "spinner",
  "map",
  "pin",
  "place",
  "destination",
  "GPS",
  "geolocation",
  "man",
  "masculinity",
  "moon",
  "night",
  "dark",
  "celestial",
  "orbit",
  "lunar",
  "astronomy",
  "nighttime",
  "widget",
  "math symbol",
  "equation",
  "algorithm",
  "computation",
  "algebra",
  "close",
  "compose",
  "write down",
  "notebook",
  "memo",
  "checked",
  "edit notes",
  "note-taking",
  "documentation",
  "edit option",
  "card",
  "additional",
  "annotate",
  "invisible note",
  "hidden information",
  "silent",
  "undisclosed",
  "note multiply",
  "notation",
  "inquiry",
  "research",
  "bookmark",
  "erase",
  "viewable",
  "sticky note",
  "comment",
  "achievement",
  "goal",
  "accuracy",
  "bullseye",
  "aim",
  "hit",
  "performance",
  "accomplish",
  "article",
  "blog",
  "efficiency",
  "optimization",
  "efficient",
  "speedometer",
  "gps",
  "point of interest",
  "geo",
  "clean",
  "line icon",
  "Pointer",
  "Indicator",
  "Guide",
  "Element",
  "Design",
  "crosshair",
  "cursor",
  "target",
  "hand",
  "targeting",
  "mouse pointer",
  "applications",
  "websites",
  "fat style",
  "puzzle",
  "interrogation",
  "bold",
  "seek",
  "segment",
  "categorization",
  "segmentation",
  "gear",
  "cogwheel",
  "configuration",
  "settings menu",
  "preferences menu",
  "adjustments",
  "controls",
  "gears",
  "setup",
  "customization",
  "daylight",
  "warmth",
  "positivity",
  "bright",
  "chat",
  "conversation",
  "dialogue",
  "bubble",
  "talk",
  "speech bubble",
  "texting",
  "comments",
  "text bubble",
  "speech balloon",
  "chatting",
  "commenting",
  "conversations",
  "messages",
  "conversation bubbles",
  "creation",
  "unhappy",
  "done",
  "selected",
  "acknowledged",
  "iconography",
  "secrecy",
  "transparency",
  "disguise",
  "Question mark",
  "Help",
  "Query",
  "Question",
  "Inquiry",
  "Sign",
  "squared",
  "functionality",
  "availability",
  "active",
  "visible option",
  "enabled",
  "equal sides",
  "certification",
  "seal",
  "fat icon",
  "star icon",
  "favorite icon",
  "rating icon",
  "rating system",
  "outlined",
  "letter m",
  "image",
  "sticker",
  "timer",
  "countdown",
  "stopwatch",
  "watch",
  "clear",
  "reduce",
  "light",
  "day",
  "sunny",
  "heat",
  "conversation deletion",
  "sad",
  "disappointed",
  "brokenhearted",
  "discussion",
  "precision",
  "aiming",
  "concentric circles",
  "alignment",
  "formatting",
  "word processing",
  "alignment tool",
  "align",
  "paragraph",
  "text box",
  "justify",
  "text-align",
  "justification",
  "design tool",
  "text formatting",
  "adjustment",
  "order",
  "desc",
  "descending",
  "text align",
  "style",
  "indentation",
  "CSS",
  "text content",
  "indent",
  "font",
  "italic",
  "strike",
  "annotation",
  "sortable",
  "ascending",
  "sort",
  "123",
  "alphabetical",
  "A-Z",
  "127",
  "Descending order",
  "Alphabetical",
  "List",
  "Data",
  "Arrangement",
  "descending order",
  "alphabetically",
  "numerically",
  "Z to A",
  "large to small",
  "filter",
  "text manipulation",
  "paragraphs",
  "underline",
  "font style",
  "cold",
  "freezing",
  "winter",
  "chilly",
  "temperature gauge",
  "temperature icon",
  "time tracking",
  "discard",
  "bin",
  "garbage",
  "waste",
  "dispose",
  "trash",
  "trash can",
  "info icon",
  "play button",
  "geometric",
  "register",
  "sign up",
  "member",
  "account",
  "new user",
  "admin",
  "permission",
  "users",
  "team",
  "project",
  "social",
  "community",
  "customer",
  "login",
  "personality",
  "individual",
  "members",
  "noticeable",
  "prominent",
  "seeing",
  "see",
  "insight",
  "expose",
  "observe",
  "sight",
  "wheelchair",
  "mobility",
  "disability",
  "inclusion",
  "assistive technology",
  "diversity",
  "inclusivity",
  "handicap",
  "airport",
  "arrival",
  "airplane",
  "terminal",
  "landing",
  "wayfinding",
  "transportation",
  "visitor",
  "departures",
  "flights",
  "aircraft",
  "tourism",
  "vacation",
  "journey",
  "departure",
  "airline",
  "boarding",
  "Airport",
  "Transfer",
  "Terminal",
  "Service",
  "Transportation",
  "Travel",
  "Wayfinding",
  "airport transfer",
  "shuttle",
  "airport shuttle",
  "transfer service",
  "transit",
  "pickup",
  "Water",
  "Maritime",
  "Point of interest",
  "Location",
  "Sea",
  "Ocean",
  "Sailor",
  "Boat",
  "Bicycle",
  "Surfboard",
  "Rental",
  "Station",
  "Tourism",
  "Beach",
  "Outdoor",
  "Adventure",
  "Recreation",
  "bike",
  "cycling",
  "route",
  "path",
  "exercise",
  "recreation",
  "briefcase",
  "cross",
  "unavailable",
  "service",
  "Vehicle",
  "Automobile",
  "Road",
  "Driving",
  "Car park",
  "Traffic",
  "Route",
  "Crossed out",
  "Canceled",
  "Unavailable",
  "Not accessible",
  "Map",
  "Destination",
  "Signage",
  "Marker",
  "cruise",
  "ship",
  "boat",
  "ocean",
  "nautical",
  "passenger",
  "Elevator",
  "Indoor",
  "Floor",
  "Lift",
  "Accessibility",
  "Elevator 2",
  "Indication",
  "Maps",
  "Facility",
  "Levels",
  "Escalator",
  "Down",
  "Stairs",
  "Public",
  "Public spaces",
  "Urban",
  "sail",
  "marine",
  "vessel",
  "Emergency",
  "Safety",
  "Equipment",
  "Extinguish",
  "Protection",
  "Fire Safety",
  "Emergency Procedure",
  "Fire Prevention",
  "First Aid",
  "Fire",
  "Hose",
  "Spray",
  "Flowing",
  "Rescue",
  "Firefighting",
  "danger",
  "exit",
  "emergency evacuation",
  "Gravestone",
  "Cemetery",
  "Burial ground",
  "Memorial",
  "Death",
  "Tombstone",
  "Old",
  "Vintage",
  "Rest in peace",
  "Burial",
  "Funeral",
  "Headstone",
  "RIP",
  "grave",
  "tombstone",
  "memorial",
  "death",
  "burial",
  "funeral",
  "cemetery",
  "remembrance",
  "mourning",
  "headstone",
  "luggage belt",
  "baggage claim",
  "suitcase",
  "Luggage",
  "Locker",
  "Baggage",
  "Security",
  "Railway",
  "Trolley",
  "Train station",
  "Cart",
  "baggage",
  "trip",
  "Metro",
  "Subway",
  "Public Transport",
  "Underground",
  "Public transportation",
  "Transportation symbol",
  "Digital interface",
  "Wayfinding system",
  "no smoking",
  "no smoking sign",
  "cigarette free",
  "smoking ban",
  "public area",
  "prohibition",
  "Cigarette",
  "Prohibition",
  "Health",
  "Warning",
  "Rule",
  "Forbidden",
  "Smoking Ban",
  "Policy",
  "Anti-smoking",
  "palm tree",
  "island",
  "wave",
  "tropical",
  "beach",
  "seaside",
  "Nature",
  "Vacation",
  "Tropical",
  "Exotic",
  "Resort",
  "Parasol",
  "Island",
  "Wave",
  "Scenic",
  "parasol",
  "umbrella",
  "sun protection",
  "plaster",
  "first aid",
  "healing",
  "injury",
  "treatment",
  "bandage",
  "care",
  "hospital",
  "First aid",
  "Injury",
  "Medical supplies",
  "Treatment",
  "Healthcare",
  "Medical facilities",
  "car",
  "rental",
  "vehicle",
  "hire",
  "temporary",
  "surveillance",
  "monitoring",
  "CCTV",
  "security system",
  "watchful",
  "sea",
  "Pathfinding",
  "Guidance",
  "Orientation",
  "smoking",
  "designated area",
  "public spaces",
  "cigarette",
  "allowed",
  "stairs",
  "lower level",
  "basement",
  "directional signage",
  "levels",
  "indoor navigation",
  "steps",
  "escalator",
  "taxi",
  "ride",
  "cab",
  "urban",
  "public",
  "Train",
  "Track",
  "Public transport",
  "public transport",
  "railway",
  "station",
  "public transit",
  "platform"
]