export const tags = [
  "design",
  "colors",
  "selection",
  "organize",
  "digital",
  "image processing",
  "electronic devices",
  "red",
  "green",
  "blue",
  "line",
  "horizontal",
  "separator",
  "connection",
  "break",
  "pair",
  "parallel",
  "social media",
  "web",
  "communication",
  "pound sign",
  "number sign",
  "tagging",
  "trend",
  "metadata",
  "underline",
  "horizontal line",
  "typography",
  "emphasis"
]