export const IconTags = [
  "movement",
  "progress",
  "wildlife",
  "nature",
  "step",
  "walking",
  "hiking",
  "motion",
  "conservation",
  "insect",
  "beauty",
  "transformation",
  "growth",
  "wings",
  "graceful",
  "flutter",
  "symbol",
  "cat",
  "pet",
  "feline",
  "kitten",
  "whiskers",
  "cute",
  "adorable",
  "animal lover",
  "domestic",
  "mammal",
  "head",
  "playful",
  "mascot",
  "ears",
  "big eyes",
  "domestic animals",
  "meow",
  "purr",
  "fluffy",
  "aquatic",
  "marine life",
  "sea creature",
  "aquarium",
  "fishing",
  "aquatic animal",
  "underwater",
  "ocean",
  "river",
  "fish",
  "swimming",
  "water",
  "ocean life",
  "marine biology",
  "jelly",
  "tentacles",
  "marine animal",
  "seafood",
  "claws",
  "crustacean",
  "delicacy",
  "vibrant",
  "sea",
  "blowfish",
  "spiky",
  "pufferfish",
  "ocean creature",
  "star shape",
  "marine fauna",
  "marine organism",
  "marine species",
  "creature",
  "mollusk",
  "cephalopod",
  "stingray",
  "cartilaginous fish",
  "flat body",
  "barbed stinger",
  "sea ray",
  "shark",
  "reptile",
  "slow",
  "patience",
  "wisdom",
  "longevity",
  "shell",
  "animal",
  "whale",
  "marine",
  "oceanography",
  "arrow",
  "navigation",
  "direction",
  "pointer",
  "24x24",
  "icon",
  "interface",
  "graphic",
  "down",
  "corner",
  "turn",
  "angular",
  "shape",
  "left",
  "navigate",
  "back",
  "previous",
  "right",
  "up",
  "scroll",
  "point",
  "indicator",
  "web",
  "button",
  "pause",
  "stop",
  "diagonal",
  "pointing",
  "interruption",
  "termination",
  "diagonal arrow",
  "end",
  "terminating arrow",
  "arrow icon",
  "bottom-left",
  "top right",
  "bottom left",
  "split arrow",
  "top-left",
  "bottom-right",
  "tl",
  "br",
  "halt",
  "top left",
  "bottom right",
  "split",
  "user interface",
  "interaction",
  "directional",
  "transition",
  "arrow down",
  "copy",
  "duplicate",
  "downward",
  "action",
  "content",
  "move",
  "item",
  "UI",
  "scrolling",
  "download",
  "downwards",
  "file transfer",
  "data transfer",
  "corner arrow",
  "arrow head",
  "pointing down",
  "angle",
  "upward",
  "rightward",
  "arrow-headed",
  "upwards",
  "UI design",
  "graphic design",
  "moving upwards",
  "higher level",
  "progression",
  "design",
  "top-right",
  "dynamic",
  "separation",
  "division",
  "bottom",
  "top",
  "triangle",
  "arrowhead",
  "down arrow",
  "instruction",
  "decrease",
  "triangular",
  "arrow-headed-download",
  "technology",
  "internet",
  "centered",
  "focus",
  "central",
  "location",
  "guidance",
  "pointy",
  "vector",
  "inward",
  "options",
  "choice",
  "switch",
  "interface design",
  "app",
  "traffic",
  "warning",
  "sign",
  "safety",
  "Left arrow",
  "Pointing",
  "Direction",
  "Navigation",
  "Back",
  "Symbol",
  "Arrowhead",
  "Simple",
  "Minimalistic",
  "expansion",
  "zoom out",
  "external",
  "refresh",
  "reload",
  "circular motion",
  "digital design",
  "circular arrow",
  "update",
  "opposite direction",
  "loop",
  "restart",
  "circular",
  "symmetric",
  "opposite",
  "sync",
  "return",
  "revert",
  "undo",
  "website",
  "reverse",
  "forward",
  "next",
  "simple",
  "minimalist",
  "basic",
  "rotate",
  "counter-clockwise",
  "rotate icon",
  "rotation",
  "angled",
  "change",
  "previous state",
  "rotate object",
  "rotate element",
  "rounded",
  "share",
  "transfer",
  "spread",
  "communication",
  "social media",
  "networking",
  "information",
  "flowchart",
  "divergence",
  "paths",
  "splitting",
  "branching",
  "diagrams",
  "expand",
  "distribution",
  "two-way",
  "lr",
  "bidirectional",
  "exchange",
  "twoway",
  "Horizontal",
  "Two-way",
  "Arrowheads",
  "Movement",
  "Interaction",
  "Opposite directions",
  "Directional",
  "Communication",
  "vertical",
  "toggle",
  "sorting",
  "dual",
  "transport",
  "control",
  "alert",
  "upload",
  "send",
  "uploading icon",
  "center",
  "arrows",
  "inwards",
  "invert",
  "arrow left",
  "arrow right",
  "left arrow",
  "stop sign",
  "Left",
  "Previous",
  "Move",
  "Navigate",
  "Button",
  "outward",
  "renew",
  "renewal",
  "up arrow",
  "bi-directional",
  "curve",
  "back to top",
  "go to top",
  "cancel",
  "horizontal",
  "proceed",
  "clockwise",
  "spin",
  "turning",
  "reposition",
  "leftwards",
  "connection",
  "collaboration",
  "skip",
  "fast-forward",
  "sequence",
  "fast forward",
  "video editing",
  "media player",
  "jump",
  "multimedia",
  "digital",
  "branching out",
  "directions",
  "decision",
  "separate",
  "diverge",
  "thick",
  "web design",
  "click",
  "moving",
  "thick arrow",
  "bold arrow",
  "bold",
  "icon design",
  "UX",
  "continue",
  "tall",
  "page",
  "document",
  "tall arrow",
  "move up",
  "increase",
  "Arrow",
  "Top",
  "Right",
  "Pointer",
  "Vertical",
  "Thick",
  "wide",
  "chevron",
  "time",
  "past",
  "history",
  "clock",
  "timeline",
  "flow",
  "memory",
  "recent",
  "updates",
  "activity",
  "shift",
  "swap",
  "mirror",
  "relocation",
  "position",
  "leftright",
  "right to left",
  "horizontal arrow",
  "reversible",
  "cycle",
  "collapse",
  "selection",
  "Sort",
  "Scroll",
  "UpDown",
  "User Interface",
  "elevate",
  "ascend",
  "data",
  "file",
  "connect",
  "link",
  "arrowheads",
  "interactive",
  "network",
  "disconnect",
  "remove",
  "modern",
  "sleek",
  "chevron double down",
  "reveal",
  "double arrow",
  "arrow symbol",
  "double",
  "process",
  "stacked",
  "show more",
  "dropdown",
  "menu",
  "select",
  "restaurant",
  "beverage",
  "culinary",
  "refreshment",
  "eatery",
  "bar",
  "cooking",
  "dining",
  "snack",
  "drink container",
  "liquids",
  "container",
  "hydration",
  "glassware",
  "liquid storage",
  "drinking",
  "water bottle",
  "drink containers",
  "beverages",
  "plastic bottles",
  "storage",
  "refreshments",
  "containers",
  "drinks",
  "bread slice",
  "bread",
  "slice",
  "food",
  "bakery",
  "sandwich",
  "breakfast",
  "carbohydrate",
  "toast",
  "coffee",
  "cafe",
  "morning",
  "drink",
  "hot",
  "relaxation",
  "mug",
  "brew",
  "machine",
  "brewing",
  "dispensing",
  "hot drinks",
  "home appliance",
  "office equipment",
  "coffee shop",
  "Coffee",
  "Beverage",
  "Caffeine",
  "Drink",
  "Ingredient",
  "Roasted",
  "Aroma",
  "Morning",
  "Espresso",
  "Bean",
  "alcohol",
  "drinkware",
  "liquor",
  "celebrate",
  "party",
  "luxury",
  "cocktail",
  "espresso",
  "coffee culture",
  "morning routines",
  "caffeine",
  "espresso maker",
  "Machine",
  "E61",
  "Barista",
  "Brewing",
  "Cafe",
  "Hot Beverage",
  "Bar",
  "barista",
  "hot drink",
  "kitchen appliance",
  "pistol",
  "burger",
  "fast food",
  "popular",
  "device",
  "hot beverage",
  "coffee maker",
  "celebration",
  "nightlife",
  "winery",
  "alarm",
  "bell",
  "notification",
  "reminder",
  "sound",
  "ringing",
  "emergency",
  "loud",
  "urgent",
  "attention",
  "media",
  "art supplies",
  "painting",
  "drawing",
  "creative",
  "artists",
  "crafting",
  "materials",
  "tools",
  "inspiration",
  "hobby",
  "audio waves",
  "sound waves",
  "music",
  "audio visualizer",
  "waveform",
  "song",
  "audio",
  "music player",
  "acoustic",
  "connectivity",
  "wireless",
  "smart devices",
  "short range",
  "electronics",
  "photography",
  "video recording",
  "picture",
  "film",
  "capture",
  "snapshot",
  "paste",
  "notes",
  "record",
  "save",
  "text",
  "art",
  "color selection",
  "creativity",
  "digital art",
  "palette",
  "color picker",
  "RGB",
  "color channels",
  "spectrum",
  "editing",
  "graphics",
  "visual",
  "color",
  "swatches",
  "tool",
  "artist",
  "computer",
  "desktop",
  "icons",
  "shortcuts",
  "files",
  "organization",
  "screen",
  "computing",
  "camera",
  "analog",
  "vintage",
  "photo",
  "photograph",
  "retro",
  "cinema",
  "roll",
  "video games",
  "gaming",
  "console",
  "controller",
  "joystick",
  "entertainment",
  "classic",
  "arcade",
  "leisure",
  "fun",
  "listening",
  "headset",
  "earphones",
  "devices",
  "streaming",
  "highlight",
  "mark",
  "emphasis",
  "important",
  "images",
  "artwork",
  "player",
  "portable",
  "work",
  "laptop",
  "keyboard",
  "email",
  "envelope",
  "message",
  "inbox",
  "correspondence",
  "open",
  "letter",
  "outbox",
  "contact",
  "video",
  "microphone",
  "voice command",
  "sound input",
  "messaging",
  "recording device",
  "note",
  "single",
  "melody",
  "musical",
  "tune",
  "listen",
  "nes",
  "video game",
  "buttons",
  "character",
  "yellow",
  "eating",
  "maze",
  "ghosts",
  "paint",
  "roller",
  "decoration",
  "renovation",
  "craft",
  "project",
  "flight",
  "backward",
  "rewind",
  "play",
  "skip forward",
  "advance",
  "track",
  "playlist",
  "playback",
  "pause button",
  "start",
  "media control",
  "beginning",
  "office",
  "equipment",
  "printing",
  "paper",
  "paperwork",
  "output",
  "print job",
  "record button",
  "movies",
  "videos",
  "film reel",
  "old-fashioned",
  "nostalgia",
  "projection",
  "traditional",
  "tablet",
  "landscape",
  "display",
  "touchscreen",
  "gadget",
  "television",
  "broadcast",
  "watching",
  "shows",
  "channel",
  "program",
  "code",
  "programming",
  "command",
  "developer",
  "system",
  "administrator",
  "IT",
  "recording",
  "recordings",
  "clips",
  "footage",
  "mute",
  "speaker",
  "volume",
  "adjust",
  "level",
  "sound control",
  "volume up",
  "volume down",
  "audible",
  "third level",
  "silence",
  "no sound",
  "quiet",
  "no volume",
  "volume control",
  "mute icon",
  "Internet",
  "Online",
  "Web design",
  "Digital",
  "Technology",
  "Browser",
  "Homepage",
  "URL",
  "Hyperlink",
  "Search",
  "wifi",
  "signal",
  "bars",
  "signal strength",
  "round",
  "strength",
  "AI",
  "artificial intelligence",
  "futuristic",
  "robot",
  "smart",
  "innovation",
  "mind",
  "blocked",
  "letters",
  "obstacles",
  "limitations",
  "access",
  "difficulty",
  "restrictions",
  "challenges",
  "Letters",
  "Circles",
  "Artificial intelligence",
  "Alphabet",
  "Symbolic",
  "Science",
  "merge",
  "logo",
  "typing",
  "web development",
  "virtual reality",
  "HTML",
  "framework",
  "VR experience",
  "A-Frame",
  "3D modeling",
  "web components",
  "immersive",
  "Artwork",
  "Frame",
  "Decoration",
  "Picture",
  "Gallery",
  "Display",
  "Interior design",
  "Home decor",
  "Wall art",
  "Design element",
  "cookout",
  "grill",
  "outdoor cooking",
  "picnic",
  "barbecue tools",
  "summer",
  "searing",
  "flame",
  "bathroom essentials",
  "toiletries",
  "personal care",
  "hygiene",
  "products",
  "shower",
  "bath",
  "cleanliness",
  "amenities",
  "restroom",
  "exploration",
  "adventure",
  "observation",
  "view",
  "search",
  "find",
  "zoom",
  "distance",
  "magnify",
  "optics",
  "appliance",
  "kitchen",
  "mixing",
  "blending",
  "food preparation",
  "electric",
  "motor",
  "kitchenware",
  "books",
  "shelves",
  "library",
  "home",
  "decor",
  "literature",
  "reading",
  "intelligence",
  "knowledge",
  "education",
  "science",
  "psychology",
  "medicine",
  "cognition",
  "branch",
  "leaves",
  "environment",
  "ecology",
  "organic",
  "tree",
  "plant",
  "extension",
  "floral",
  "botanical",
  "leaf",
  "flora",
  "foliage",
  "light bulb",
  "ideas",
  "electricity",
  "illumination",
  "energy",
  "solution",
  "invention",
  "desert",
  "succulent",
  "thorny",
  "arid climate",
  "botany",
  "camping",
  "vehicle",
  "recreation",
  "vacation",
  "holiday",
  "road trip",
  "outdoors",
  "caravan",
  "travel",
  "group",
  "journey",
  "expedition",
  "pack",
  "semiconductor",
  "microchip",
  "silicon chip",
  "processor",
  "component",
  "circuit",
  "cleaning",
  "household",
  "chores",
  "bucket",
  "soap",
  "cleanup",
  "sanitation",
  "maintenance",
  "spray",
  "cleaning product",
  "sanitize",
  "disinfect",
  "Storage",
  "Wardrobe",
  "Home",
  "Organization",
  "Room",
  "Household",
  "Clothes",
  "Shoes",
  "Personal items",
  "money",
  "wealth",
  "currency",
  "business",
  "financial",
  "savings",
  "earnings",
  "transactions",
  "finance",
  "economy",
  "orientation",
  "mapping",
  "geography",
  "north",
  "south",
  "east",
  "west",
  "geometry",
  "dimensional",
  "volumetric",
  "space",
  "perspective",
  "solid",
  "structure",
  "learning",
  "school",
  "graduation",
  "pencils",
  "study",
  "teaching",
  "lesson",
  "Factory",
  "Arm",
  "Manufacturing",
  "Production",
  "Industries",
  "Automation",
  "Machinery",
  "Assembly lines",
  "Industrial revolution",
  "factory",
  "industrial",
  "manufacturing",
  "machinery",
  "automation",
  "production",
  "assembly line",
  "conveyor belt",
  "mechanical",
  "building",
  "facility",
  "workplace",
  "biometric",
  "security",
  "authentication",
  "identification",
  "privacy",
  "scan",
  "digit",
  "unique",
  "danger",
  "exit",
  "heat",
  "emergency evacuation",
  "cooling",
  "food storage",
  "chill",
  "refrigeration",
  "fridge",
  "bed",
  "double bed",
  "bedroom",
  "furniture",
  "interior",
  "sleep",
  "cozy",
  "rest",
  "comfort",
  "king",
  "interior design",
  "home decor",
  "accommodation",
  "hotel",
  "Bed",
  "Sleep",
  "Rest",
  "Comfort",
  "Furniture",
  "Interior",
  "Decor",
  "Relaxation",
  "bedside",
  "table",
  "nightstand",
  "room",
  "chair",
  "seating",
  "furnishings",
  "living room",
  "seat",
  "furnishing",
  "comfortable",
  "style",
  "contemporary",
  "Chair",
  "Seat",
  "Sitting",
  "Living room",
  "couch",
  "lounge",
  "stylish",
  "home furnishings",
  "4-seater",
  "sofa",
  "Desk",
  "Table",
  "Wooden",
  "Office",
  "Workspace",
  "Workstation",
  "Home office",
  "Furniture ",
  "cabinet",
  "drawers",
  "wood",
  "organize",
  "analysis",
  "chart",
  "statistics",
  "graph",
  "upward trend",
  "data analysis",
  "presentation",
  "report",
  "hairdryer",
  "hair styling",
  "hair care",
  "blow dryer",
  "grooming",
  "salon",
  "hair tools",
  "hair accessories",
  "Hill",
  "Landscape",
  "Nature",
  "Scenery",
  "Outdoors",
  "Tranquility",
  "Mountains",
  "Beautiful",
  "View",
  "Background",
  "brainstorming",
  "creative thinking",
  "imagination",
  "strategy",
  "concept",
  "chimney",
  "smoke",
  "industrialization",
  "industry",
  "engineering",
  "metal",
  "material",
  "heavy",
  "silver",
  "construction",
  "iron",
  "workmanship",
  "strong",
  "cutlery",
  "utensils",
  "meal",
  "preparation",
  "silverware",
  "kitchen tools",
  "scenic",
  "mountains",
  "trees",
  "reflection",
  "serene",
  "calm",
  "relaxing",
  "panoramic",
  "green",
  "fresh",
  "plants",
  "natural",
  "soap dispenser",
  "liquid soap",
  "bathroom accessory",
  "household item",
  "body wash",
  "hand sanitizer",
  "disinfectant",
  "handwashing",
  "bathroom",
  "healthcare",
  "villa",
  "resort",
  "house",
  "estate",
  "architecture",
  "property",
  "residence",
  "real estate",
  "heating",
  "electromagnetic radiation",
  "meal prep",
  "quick",
  "convenient",
  "leftovers",
  "cash",
  "banking",
  "payment",
  "prosperity",
  "Wealth",
  "Finance",
  "Prosperity",
  "Savings",
  "Investments",
  "Business",
  "Riches",
  "Currency",
  "Earnings",
  "Cash",
  "mountain",
  "tranquility",
  "Kitchen",
  "Appliance",
  "Cooking",
  "Baking",
  "Food",
  "Heat",
  "Temperature",
  "eco-friendly",
  "freshness",
  "sustainability",
  "politician",
  "government",
  "leadership",
  "elections",
  "public speaking",
  "speech",
  "public appearance",
  "politics",
  "politician icon",
  "political event",
  "authority",
  "election",
  "official",
  "candidate",
  "decision-making",
  "launch",
  "spacecraft",
  "rocketship",
  "fast",
  "outer space",
  "window covering",
  "shades",
  "protection",
  "light filtering",
  "room decor",
  "sunlight control",
  "shield",
  "defense",
  "armor",
  "guard",
  "safeguard",
  "sentry",
  "shielding",
  "secure",
  "safe",
  "secure environment",
  "fortress",
  "shield wall",
  "armour",
  "shield logo",
  "secure icon",
  "line",
  "resilience",
  "Oven",
  "Burner",
  "Cuisine",
  "Chef",
  "surfing",
  "beach",
  "sports",
  "waves",
  "pool",
  "swim",
  "religion",
  "worship",
  "faith",
  "culture",
  "historical",
  "ancient",
  "sacred",
  "spirituality",
  "Religious",
  "Spiritual",
  "Building",
  "Worship",
  "Faith",
  "Culture",
  "Tradition",
  "Sacred",
  "Architecture",
  "Icon",
  "tent",
  "wilderness",
  "outdoor",
  "shelter",
  "campsite",
  "explore",
  "toy",
  "blocks",
  "children",
  "toys",
  "educational",
  "kids",
  "playtime",
  "childhood",
  "games",
  "colors",
  "stacking",
  "game",
  "toy head",
  "forest",
  "branches",
  "park",
  "Rustic",
  "Cozy",
  "Living space",
  "Unique",
  "Tree",
  "House",
  "Shelter",
  "Cabin",
  "Outdoor",
  "greenery",
  "scenery",
  "woodland",
  "trunk",
  "stylized",
  "minimal",
  "tree trunk",
  "forestry",
  "texture",
  "rings",
  "timber",
  "alien",
  "flying saucer",
  "science fiction",
  "extraterrestrial",
  "flying object",
  "ballot",
  "survey",
  "voting",
  "choose",
  "poll",
  "shopping",
  "pocket",
  "credit card",
  "personal belongings",
  "wallet",
  "laundry",
  "clothing",
  "fabric",
  "detergent",
  "washing",
  "electric kettle",
  "boiling water",
  "hot beverages",
  "tea",
  "instant noodles",
  "Yurt",
  "Nomadic",
  "Central Asia",
  "Portable",
  "Tent",
  "Traditional",
  "Dwelling",
  "Round",
  "Skins",
  "Felt",
  "baby stroller",
  "parenting",
  "family",
  "childcare",
  "infant",
  "baby products",
  "pram",
  "baby carriage",
  "stroller",
  "baby gear",
  "T-shirt",
  "Clothing",
  "Fashion",
  "Style",
  "Apparel",
  "Casual",
  "Wearable",
  "Garment",
  "textile",
  "fiber",
  "fashion",
  "soft",
  "gardening",
  "outdoor living",
  "home improvement",
  "landscaping",
  "flowers",
  "patio",
  "allergies",
  "sensitive skin",
  "irritation-free",
  "hypoallergenic",
  "skin care",
  "cosmetics",
  "wellness",
  "gentle",
  "no leaks",
  "leak-proof",
  "leak-resistant",
  "prevention",
  "guarantee",
  "quality",
  "repair",
  "job",
  "career",
  "briefcase",
  "luggage",
  "professional",
  "employment",
  "Bag",
  "Cart",
  "Handle",
  "Online shopping",
  "E-commerce",
  "Retail",
  "Purchase",
  "Consumerism",
  "Market",
  "Shop",
  "Store",
  "Add to cart",
  "Buy",
  "Commerce",
  "Discount",
  "Sale",
  "Offer",
  "Shopping Bag",
  "Promotion",
  "Shopping Cart",
  "Value",
  "Marketplace",
  "Shopaholic",
  "Basket",
  "Items",
  "shopping basket",
  "cart",
  "online shopping",
  "ecommerce",
  "add to cart",
  "purchase",
  "digital shopping",
  "shopping icon",
  "retail",
  "virtual basket",
  "e-commerce",
  "speedy checkout",
  "fast delivery",
  "shopping app",
  "digital commerce",
  "ecommerce website",
  "online",
  "store",
  "shop",
  "buy",
  "items",
  "price",
  "sale",
  "label",
  "product",
  "tag",
  "labels",
  "prices",
  "promotions",
  "marketing",
  "special",
  "decorative",
  "artistic",
  "distinctive",
  "baht",
  "Thai",
  "foreign exchange",
  "currency symbol",
  "Thailand",
  "dice",
  "random",
  "number",
  "one",
  "luck",
  "casino",
  "probability",
  "chance",
  "two",
  "gambling",
  "dice roll",
  "three",
  "randomness",
  "dice game",
  "board game",
  "cube",
  "rolling",
  "numeric",
  "numbers",
  "board games",
  "seven",
  "random number",
  "game interface",
  "nine",
  "2",
  "numeral",
  "tech",
  "Three",
  "Number",
  "Counting",
  "Digit",
  "Modern",
  "Sleek",
  "Typography",
  "Numeric",
  "four",
  "quantity",
  "value",
  "counter",
  "digital style",
  "textbox",
  "five",
  "counting",
  "six",
  "special character",
  "calculator",
  "electronic",
  "eight",
  "score",
  "typography",
  "zero",
  "dollar sign",
  "cost",
  "eurozone",
  "Europe",
  "math",
  "percentage",
  "ratio",
  "proportion",
  "pound",
  "hash",
  "number sign",
  "coding",
  "punctuation",
  "permillage",
  "concentration",
  "blood alcohol content",
  "mathematics",
  "unit",
  "measurement",
  "fraction",
  "Russia",
  "ruble",
  "Russian rubles",
  "Indian rupee",
  "INR",
  "monetary unit",
  "India",
  "monetary",
  "female",
  "gender",
  "woman",
  "feminine",
  "ladies",
  "feminist",
  "equality",
  "women's rights",
  "Male",
  "Gender",
  "Masculinity",
  "Men",
  "Man",
  "Characteristic",
  "Information",
  "Identity",
  "gender-neutral",
  "male",
  "inclusive",
  "signage",
  "unisex",
  "dots",
  "more",
  "settings",
  "actions",
  "ellipsis",
  "three dots",
  "list",
  "context menu",
  "option",
  "kebab",
  "major",
  "points",
  "special characters",
  "minor",
  "intersection",
  "elements",
  "break",
  "spacing",
  "divider",
  "lines",
  "design element",
  "eye-catching",
  "Japan",
  "currency-symbol",
  "yen",
  "Japanese",
  "Asian",
  "basketball",
  "ball",
  "sport",
  "hoop",
  "dribble",
  "team",
  "competition",
  "athlete",
  "football",
  "soccer",
  "sporting equipment",
  "team sport",
  "athletics",
  "goal",
  "rugby",
  "rugby ball",
  "sports equipment",
  "oval",
  "leather",
  "synthetic",
  "field sport",
  "contact sport",
  "tennis",
  "athleticism",
  "sportsmanship",
  "racket",
  "person",
  "accessibility",
  "circle",
  "user-friendly",
  "disabled",
  "special needs",
  "easy access",
  "universal design",
  "Person",
  "Inclusivity",
  "Disability",
  "Diversity",
  "Assistance",
  "Support",
  "User-friendly",
  "Equality",
  "Inclusive design",
  "Adaptive",
  "plus",
  "join",
  "insert",
  "create",
  "fat",
  "add",
  "append",
  "new",
  "plus sign",
  "square",
  "45 degrees",
  "element",
  "45 degree",
  "address",
  "username",
  "handle",
  "email address",
  "block",
  "partials",
  "sections",
  "arrange",
  "grouping",
  "board",
  "section",
  "multi-column",
  "layout",
  "dashboard",
  "boards",
  "vertical layout",
  "application",
  "multiple",
  "analytics",
  "expandable",
  "multi-directional",
  "multi",
  "columns",
  "grid",
  "panels",
  "tiles",
  "ui",
  "tabs",
  "multi-tab",
  "arrangement",
  "workspace",
  "multiply",
  "operation",
  "calculation",
  "calculators",
  "mathematical",
  "divided",
  "three columns",
  "divide",
  "partition",
  "interface element",
  "components",
  "segmented",
  "template",
  "effect",
  "split view",
  "split screen",
  "segments",
  "subtraction",
  "delete",
  "minus",
  "deduct",
  "physical",
  "bookshelf",
  "paperback",
  "novel",
  "book",
  "pages",
  "story",
  "side view",
  "academic",
  "publication",
  "ebook",
  "textbook",
  "box",
  "closed",
  "package",
  "delivery",
  "sealed",
  "enclosed",
  "packing",
  "inside",
  "packaging",
  "restricted",
  "outline",
  "rectangle",
  "shipping",
  "parcel",
  "carton",
  "unpack",
  "context",
  "placeholder",
  "containment",
  "child",
  "youth",
  "avatar",
  "kid",
  "profile",
  "human",
  "heartbreak",
  "sadness",
  "emotions",
  "love",
  "relationship",
  "romantic",
  "disappointment",
  "broken heart",
  "heart",
  "broken",
  "romance",
  "feelings",
  "bug",
  "error",
  "issue",
  "problem",
  "software",
  "pest",
  "safari",
  "legs",
  "glitch",
  "place of worship",
  "holy",
  "Christianity",
  "religious symbol",
  "Residential",
  "Real Estate",
  "Housing",
  "Property",
  "Construction",
  "Roof",
  "dwelling",
  "commercial",
  "marketplace",
  "clickable",
  "task",
  "relationships",
  "check mark",
  "confirmation",
  "completion",
  "approval",
  "form",
  "check",
  "confirm",
  "submit",
  "approve",
  "validate",
  "edit",
  "pencil",
  "modify",
  "edit button",
  "editable",
  "exclamation mark",
  "like",
  "favorite",
  "emotion",
  "info",
  "details",
  "help",
  "tooltip",
  "informational",
  "hidden",
  "inactive",
  "unclickable",
  "ui element",
  "invisible",
  "interact",
  "unseen",
  "concealed",
  "arithmetic",
  "question mark",
  "support",
  "faq",
  "query",
  "FAQ",
  "assistance",
  "search engine",
  "magnifying glass",
  "search button",
  "search function",
  "input field",
  "search bar",
  "UI icon",
  "lookup",
  "star",
  "rating",
  "rate",
  "subtract",
  "calculate",
  "user",
  "account",
  "management",
  "staff",
  "login",
  "member",
  "identity",
  "visible element",
  "visible",
  "graphical user interface",
  "UI element",
  "calendar",
  "date",
  "schedule",
  "appointment",
  "event",
  "planner",
  "time management",
  "deadline",
  "tracking",
  "visualization",
  "bubbles",
  "data visualization",
  "infographic",
  "stock market",
  "investment",
  "candlestick chart",
  "charting",
  "Graph",
  "Data visualization",
  "Analytics",
  "Statistics",
  "Report",
  "Presentation",
  "Dashboard",
  "Diagram",
  "trends",
  "metrics",
  "reporting",
  "line chart",
  "plot",
  "pie",
  "tick",
  "complete",
  "confirmed",
  "success",
  "verification",
  "checkbox",
  "verified",
  "validated",
  "acceptance",
  "tasks",
  "planning",
  "progress tracking",
  "to-do list",
  "productivity",
  "validation",
  "approved",
  "correct",
  "checklist",
  "empty",
  "incomplete",
  "unchecked",
  "exclamation",
  "completed",
  "done",
  "achievement",
  "task list",
  "to do",
  "mistake",
  "checkboxes",
  "task management",
  "status",
  "issues",
  "accomplishment",
  "todo list",
  "finished",
  "tick mark",
  "zero degree",
  "Circular arrow",
  "Angle",
  "Rotation",
  "User interface",
  "Arrow icon",
  "135 degree",
  "Circular motion",
  "Circular design",
  "flip",
  "180 degrees",
  "270 degrees",
  "spinner",
  "315 degrees",
  "Clockwise",
  "Rotate",
  "90 degrees",
  "Vector",
  "unknown",
  "secret",
  "mask",
  "eliminate",
  "function",
  "addition",
  "include",
  "feature",
  "emoticon",
  "illustration",
  "ui design",
  "circled",
  "acknowledgment",
  "pen",
  "write",
  "hazard",
  "caution",
  "affection",
  "like button",
  "favorite button",
  "valentine",
  "heart shape",
  "question",
  "multiplication",
  "FAQs",
  "discover",
  "importance",
  "eye",
  "visibility",
  "Enclosed",
  "Highlight",
  "Emphasis",
  "Attention-grabbing",
  "Circular",
  "Outline",
  "Graphic design",
  "loading",
  "animation",
  "waiting",
  "loading indicator",
  "plan",
  "hour",
  "minute",
  "second",
  "timing",
  "Code",
  "Coding",
  "Programming",
  "Development",
  "Brackets",
  "Circle",
  "Syntax",
  "Snippet",
  "Syntax Highlighting",
  "development",
  "syntax",
  "brackets",
  "code editor",
  "coding standards",
  "chevrons",
  "nested",
  "open chevrons",
  "Commands",
  "Instructions",
  "Code Blocks",
  "Software",
  "Sequence",
  "Arrows",
  "corporate",
  "enterprise",
  "company logo",
  "branding",
  "3-way",
  "junction",
  "three-way",
  "route",
  "four-way",
  "links",
  "endpoint",
  "pathway",
  "alignment",
  "server",
  "dessert",
  "sweet",
  "flat design",
  "biscuit",
  "delicious",
  "indulgence",
  "crown",
  "royalty",
  "queen",
  "monarchy",
  "power",
  "regal",
  "ornate",
  "royal",
  "leader",
  "glory",
  "dislike",
  "thumb down",
  "unlike",
  "reject",
  "thumbs",
  "negative",
  "feedback",
  "expression",
  "edit content",
  "document editing",
  "customize",
  "edit tool",
  "editor",
  "swirl",
  "writing",
  "edit icon",
  "simplified",
  "minimalistic",
  "file system",
  "data management",
  "folder",
  "zip",
  "compress",
  "format",
  "archive",
  "compressed",
  "zipped",
  "binary",
  "corrupted",
  "inaccessible",
  "data loss",
  "depression",
  "cloud computing",
  "backup",
  "script",
  "programming language",
  "spreadsheet",
  "revision",
  "modification",
  "notify",
  "graphs",
  "charts",
  "attachment",
  "file-heart",
  "inspection",
  "file info",
  "metadata",
  "file type",
  "information icon",
  "confidential",
  "discreet",
  "encrypted",
  "private",
  "replicate",
  "uncertainty",
  "unsuppored",
  "browse",
  "search tool",
  "searching",
  "favorite file",
  "starred",
  "marker",
  "file management",
  "File",
  "Text",
  "Document",
  "Content",
  "Page",
  "Edit",
  "Write",
  "Read",
  "documents",
  "stack",
  "tray",
  "collection",
  "records",
  "personal",
  "accessible",
  "visible file",
  "show",
  "flag",
  "national",
  "country",
  "translation",
  "national flag",
  "two stripes",
  "patriotic",
  "emblem",
  "patriotism",
  "nationality",
  "sovereignty",
  "category",
  "language",
  "international",
  "golf",
  "target",
  "course",
  "directory",
  "folders",
  "Folder",
  "Broken heart",
  "Emotion",
  "Sadness",
  "Loss",
  "Sentimental",
  "Folder icon",
  "Heart icon",
  "Symbol icon",
  "emotional",
  "distress",
  "loss",
  "symbolic",
  "checkmark",
  "folder icon",
  "document icon",
  "file verification",
  "folder check",
  "folder validation",
  "bulk",
  "file manager",
  "bulk delete",
  "multiple items",
  "clean up",
  "enquiry",
  "unclear",
  "confusion",
  "magnifier",
  "explorer",
  "Subtract",
  "Delete",
  "Directory",
  "Management",
  "flap",
  "contents",
  "expanded",
  "hierarchy",
  "organized",
  "digital organization",
  "follow",
  "social",
  "subscribe",
  "users",
  "followers",
  "relationship status",
  "online presence",
  "notifications",
  "following",
  "following button",
  "add user",
  "interactions",
  "user account",
  "follower",
  "people",
  "representation",
  "version control",
  "repository",
  "git",
  "workflow",
  "commit",
  "comparison",
  "difference",
  "changes",
  "queue",
  "versioning",
  "VCS",
  "merge process",
  "code changes",
  "pull request",
  "source code",
  "draft",
  "work in progress",
  "code review",
  "GitLab",
  "Bitbucket",
  "GitHub",
  "review",
  "source control",
  "fork",
  "earth",
  "world",
  "globe",
  "global",
  "planet",
  "worldwide",
  "international business",
  "map",
  "globalization",
  "small",
  "Valentine's Day",
  "dating",
  "health",
  "medical",
  "pin",
  "instructions",
  "notice",
  "guide",
  "advice",
  "tips",
  "explanation",
  "Hidden",
  "Inactive",
  "Concealed",
  "Invisible element",
  "Transparent",
  "Unseen",
  "Concealed feature",
  "Concealed content",
  "hide",
  "eyes",
  "conceal",
  "stealth",
  "camouflage",
  "cloaked",
  "backspace",
  "shortcut",
  "input",
  "text editing",
  "key",
  "lock",
  "press",
  "eject",
  "safely remove",
  "log out",
  "enter key",
  "setting",
  "mac",
  "preferences",
  "entry",
  "page down",
  "pagination",
  "webpage",
  "modifier",
  "tab key",
  "arrow key",
  "layers",
  "dotted",
  "two layers",
  "overlay",
  "3",
  "layers stack",
  "levels",
  "functionality",
  "thumb",
  "react",
  "positive",
  "appreciation",
  "hyperlink",
  "redirect",
  "loading animation",
  "loading process",
  "loader",
  "wait",
  "loading screen",
  "man",
  "masculinity",
  "widget",
  "math symbol",
  "equation",
  "algorithm",
  "computation",
  "algebra",
  "close",
  "compose",
  "write down",
  "notebook",
  "memo",
  "checked",
  "edit notes",
  "note-taking",
  "documentation",
  "edit option",
  "card",
  "additional",
  "annotate",
  "invisible note",
  "hidden information",
  "silent",
  "undisclosed",
  "note multiply",
  "notation",
  "inquiry",
  "research",
  "bookmark",
  "erase",
  "user profile",
  "note symbol",
  "note user",
  "viewable",
  "sticky note",
  "comment",
  "accuracy",
  "bullseye",
  "aim",
  "hit",
  "performance",
  "accomplish",
  "article",
  "blog",
  "efficiency",
  "speed",
  "optimization",
  "efficient",
  "speedometer",
  "gps",
  "point of interest",
  "geo",
  "destination",
  "place",
  "socket",
  "outlet",
  "plug",
  "cable",
  "adapter",
  "American plug",
  "Canadian plug",
  "Mexican plug",
  "Japanese plug",
  "connector",
  "charging",
  "type-b",
  "usb",
  "cord",
  "charger",
  "type D",
  "jack plug",
  "hardware",
  "interfacing",
  "electrical",
  "clean",
  "line icon",
  "Indicator",
  "Guide",
  "Element",
  "Design",
  "crosshair",
  "cursor",
  "hand",
  "applications",
  "websites",
  "fat style",
  "puzzle",
  "interrogation",
  "detection",
  "military",
  "monitoring",
  "radar system",
  "radar",
  "scanner",
  "radar3",
  "blips",
  "surveillance",
  "scanning",
  "advanced",
  "level 5",
  "seek",
  "segment",
  "categorization",
  "segmentation",
  "gear",
  "cogwheel",
  "configuration",
  "settings menu",
  "preferences menu",
  "adjustments",
  "controls",
  "gears",
  "setup",
  "customization",
  "digging",
  "utensil",
  "implement",
  "simulation",
  "similarity",
  "virtual model",
  "imitation",
  "pattern",
  "align",
  "justify",
  "formatting",
  "paragraph",
  "justify text",
  "blank",
  "bullet points",
  "notepad",
  "type A",
  "Electricity",
  "Plug",
  "Outlet",
  "Power",
  "Type B",
  "Socket",
  "Electrical",
  "type C",
  "USB",
  "port",
  "Type D",
  "Connection",
  "Electronics",
  "Audio",
  "Video",
  "Equipment",
  "Prongs",
  "European",
  "type F",
  "type",
  "power supply",
  "socket type",
  "L-shaped",
  "chat",
  "conversation",
  "dialogue",
  "bubble",
  "talk",
  "speech bubble",
  "texting",
  "comments",
  "text bubble",
  "speech balloon",
  "chatting",
  "commenting",
  "conversations",
  "messages",
  "conversation bubbles",
  "square user",
  "creation",
  "unhappy",
  "selected",
  "acknowledged",
  "iconography",
  "secrecy",
  "transparency",
  "disguise",
  "Question mark",
  "Help",
  "Query",
  "Question",
  "Inquiry",
  "Sign",
  "squared",
  "availability",
  "active",
  "visible option",
  "enabled",
  "equal sides",
  "certification",
  "seal",
  "fat icon",
  "star icon",
  "favorite icon",
  "rating icon",
  "rating system",
  "outlined",
  "letter m",
  "sticker",
  "colorful",
  "390",
  "timer",
  "countdown",
  "stopwatch",
  "watch",
  "clear",
  "reduce",
  "conversation deletion",
  "sad",
  "disappointed",
  "brokenhearted",
  "discussion",
  "precision",
  "aiming",
  "concentric circles",
  "word processing",
  "alignment tool",
  "text box",
  "text-align",
  "justification",
  "design tool",
  "text formatting",
  "adjustment",
  "order",
  "desc",
  "descending",
  "text align",
  "indentation",
  "CSS",
  "text content",
  "indent",
  "font",
  "italic",
  "strike",
  "annotation",
  "ascending",
  "alphabetic",
  "alphabetical",
  "sort",
  "alphabet",
  "text data",
  "ascending order",
  "Descending order",
  "Alphabetical",
  "List",
  "Data",
  "Arrangement",
  "descending order",
  "alphabetically",
  "numerically",
  "Z to A",
  "large to small",
  "filter",
  "text manipulation",
  "paragraphs",
  "underline",
  "font style",
  "time tracking",
  "discard",
  "bin",
  "garbage",
  "waste",
  "dispose",
  "trash",
  "trash can",
  "info icon",
  "play button",
  "geometric",
  "registration",
  "sign-up",
  "register",
  "community",
  "sign up",
  "new user",
  "disable",
  "ban",
  "admin",
  "permission",
  "figure",
  "User",
  "Profile",
  "Heart",
  "Affection",
  "Like",
  "Social media",
  "Dating",
  "Love",
  "Relationship",
  "personnel",
  "profile picture",
  "personality",
  "customer",
  "individual",
  "members",
  "abstract",
  "customizable",
  "background",
  "trapezoid",
  "noticeable",
  "prominent",
  "seeing",
  "see",
  "insight",
  "expose",
  "observe",
  "sight",
  "timepiece",
  "wristwatch",
  "accessory",
  "personal item",
  "watch face",
  "timekeeping",
  "wheelchair",
  "mobility",
  "disability",
  "inclusion",
  "assistive technology",
  "diversity",
  "inclusivity",
  "handicap",
  "web browser",
  "browsing",
  "window",
  "windows",
  "operating system",
  "GUI",
  "multitasking",
  "Application",
  "Screen",
  "Window frame",
  "maps",
  "geolocation",
  "multiculturalism",
  "airport",
  "arrival",
  "airplane",
  "terminal",
  "landing",
  "wayfinding",
  "transportation",
  "visitor",
  "departures",
  "flights",
  "aircraft",
  "tourism",
  "departure",
  "airline",
  "boarding",
  "Airport",
  "Transfer",
  "Terminal",
  "Service",
  "Transportation",
  "Travel",
  "Wayfinding",
  "airport transfer",
  "shuttle",
  "airport shuttle",
  "transfer service",
  "transit",
  "pickup",
  "Water",
  "Maritime",
  "Point of interest",
  "Location",
  "Sea",
  "Ocean",
  "Sailor",
  "Boat",
  "Bicycle",
  "Surfboard",
  "Rental",
  "Station",
  "Tourism",
  "Beach",
  "Adventure",
  "Recreation",
  "bike",
  "cycling",
  "path",
  "exercise",
  "cross",
  "unavailable",
  "service",
  "Indoor",
  "Parking",
  "Car",
  "Vehicles",
  "Directions",
  "Guidance",
  "Automobiles",
  "Garage",
  "car",
  "parking",
  "parking lot",
  "street",
  "road",
  "lot",
  "Vehicle",
  "Automobile",
  "Road",
  "Driving",
  "Car park",
  "Traffic",
  "Route",
  "changing area",
  "clothes",
  "attire",
  "dressing room",
  "locker room",
  "changing room",
  "personal space",
  "Check in",
  "Registration",
  "Marker",
  "City bus",
  "Public transportation",
  "Urban",
  "Bus stop",
  "Transit system",
  "Crossed out",
  "Canceled",
  "Unavailable",
  "Not accessible",
  "Map",
  "Destination",
  "Signage",
  "cruise",
  "ship",
  "boat",
  "nautical",
  "passenger",
  "Elevator",
  "Floor",
  "Lift",
  "Accessibility",
  "Elevator 2",
  "Indication",
  "Maps",
  "Facility",
  "Levels",
  "Escalator",
  "Down",
  "Stairs",
  "Public",
  "Public spaces",
  "Unity",
  "Togetherness",
  "Community",
  "Parents",
  "Children",
  "Safety",
  "Nuclear family",
  "sail",
  "vessel",
  "Emergency",
  "Extinguish",
  "Protection",
  "Fire Safety",
  "Emergency Procedure",
  "Fire Prevention",
  "First Aid",
  "burning",
  "inferno",
  "campfire",
  "Fire",
  "Hose",
  "Spray",
  "Flowing",
  "Rescue",
  "Firefighting",
  "Gravestone",
  "Cemetery",
  "Burial ground",
  "Memorial",
  "Death",
  "Tombstone",
  "Old",
  "Vintage",
  "Rest in peace",
  "Burial",
  "Funeral",
  "Headstone",
  "RIP",
  "grave",
  "tombstone",
  "memorial",
  "death",
  "burial",
  "funeral",
  "cemetery",
  "remembrance",
  "mourning",
  "headstone",
  "greeting",
  "farewell",
  "roadmap",
  "welcome",
  "Path",
  "Journey",
  "GPS",
  "Explore",
  "socialization",
  "waiting area",
  "public space",
  "hospitality",
  "luggage belt",
  "baggage claim",
  "suitcase",
  "Luggage",
  "Locker",
  "Baggage",
  "Security",
  "Railway",
  "Trolley",
  "Train station",
  "baggage",
  "trip",
  "Pinpoint",
  "Exploration",
  "Cartography",
  "Landmarks",
  "Geographical",
  "Roads",
  "Points of Interest",
  "routes",
  "pathfinding",
  "Metro",
  "Subway",
  "Public Transport",
  "Underground",
  "Transportation symbol",
  "Digital interface",
  "Wayfinding system",
  "no smoking",
  "no smoking sign",
  "cigarette free",
  "smoking ban",
  "public area",
  "prohibition",
  "Cigarette",
  "Prohibition",
  "Health",
  "Warning",
  "Rule",
  "Forbidden",
  "Smoking Ban",
  "Policy",
  "Anti-smoking",
  "palm tree",
  "island",
  "wave",
  "tropical",
  "seaside",
  "Vacation",
  "Tropical",
  "Exotic",
  "Resort",
  "Parasol",
  "Island",
  "Wave",
  "Scenic",
  "parasol",
  "sun",
  "umbrella",
  "sun protection",
  "plaster",
  "first aid",
  "healing",
  "injury",
  "treatment",
  "bandage",
  "care",
  "hospital",
  "First aid",
  "Injury",
  "Medical supplies",
  "Treatment",
  "Healthcare",
  "Medical facilities",
  "targeting",
  "mouse pointer",
  "rental",
  "hire",
  "temporary",
  "Bathroom",
  "Toilet",
  "Washroom",
  "Restroom sign",
  "Public facility",
  "Hygiene",
  "Sanitation",
  "Gender-neutral restroom",
  "Restroom icon",
  "CCTV",
  "security system",
  "watchful",
  "checkpoint",
  "security measures",
  "access control",
  "authorization",
  "secure area",
  "entry point",
  "Pathfinding",
  "Orientation",
  "smoking",
  "designated area",
  "public spaces",
  "cigarette",
  "allowed",
  "stairs",
  "lower level",
  "basement",
  "directional signage",
  "indoor navigation",
  "steps",
  "escalator",
  "taxi stop",
  "pick up point",
  "public transportation",
  "map icon",
  "urban travel",
  "city life",
  "taxi",
  "ride",
  "cab",
  "urban",
  "public",
  "Train",
  "Track",
  "Public transport",
  "public transport",
  "railway",
  "station",
  "public transit",
  "platform",
  "Walking",
  "Hiking",
  "Pedestrian",
  "People",
  "pedestrian",
  "cloud",
  "lightning",
  "storm",
  "thunderstorm",
  "weather",
  "forecast",
  "climate",
  "meteorology",
  "rain",
  "precipitation",
  "rainy day",
  "weather forecast",
  "sky",
  "season",
  "partly cloudy",
  "sunshine",
  "thermometer",
  "temperature",
  "light mode",
  "dark mode",
  "weather app",
  "light",
  "dark",
  "mode",
  "variation",
  "weather website",
  "flash",
  "moon",
  "nighttime",
  "clear skies",
  "dreams",
  "night",
  "crescent moon",
  "lunar",
  "astronomy",
  "crescent",
  "clear sky",
  "daylight",
  "warmth",
  "positivity",
  "bright",
  "day",
  "sunny",
  "Sun",
  "Light mode",
  "Sunny",
  "Weather forecast",
  "Brightness",
  "Clear sky",
  "Daytime",
  "Climate",
  "Meteorology",
  "cold",
  "freezing",
  "winter",
  "chilly",
  "temperature gauge",
  "temperature icon"
]